# Generated by Django 2.0.2 on 2018-03-06 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('alias', models.CharField(max_length=250, null=True, verbose_name='alias')),
                ('abstract', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(400)], verbose_name='Abstract')),
                ('content', models.TextField(null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name_plural': 'Blogs',
                'verbose_name': 'Blog',
            },
        ),
    ]
