# Generated by Django 2.0.2 on 2018-03-08 09:41

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('alias', models.CharField(max_length=250, null=True, verbose_name='alias')),
                ('abstract', models.TextField(blank=True, null=True, validators=[
                 django.core.validators.MaxLengthValidator(400)], verbose_name='Abstract')),
                ('content', models.TextField(null=True, verbose_name='Content')),
                ('pub_date', models.DateTimeField(
                    default=django.utils.timezone.now, verbose_name='Publish Date')),
                ('is_pub', models.BooleanField(default=True, verbose_name='Publish')),
            ],
            options={
                'ordering': ['-pub_date'],
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
